#![forbid(unsafe_op_in_unsafe_fn)]

mod draw_bucket;
pub(crate) mod draw_lists;
mod external_contribution_lowering;
mod feature_extraction;
mod frame_envelope_builder;
mod frame_orchestrator;
pub(super) mod frame_snapshots;
mod frame_submit;
mod frame_types;
pub(super) mod gpu_gbuffer_indirect;
pub(super) mod gpu_indirect_stream;
pub(super) mod gpu_shadow_indirect;
mod gpu_prewarm;
pub(super) mod gpu_scene_table_upload;
pub(super) mod gpu_scene_tables;
mod input;
pub(super) mod instancing;
mod launch_loading;
mod lifecycle;
pub(crate) mod light_extraction;
pub(crate) mod lights;
mod model_residency;
pub(crate) mod passes;
mod passes_ubo;
mod picking;
mod playable_viewport;
mod postfx;
mod prelaunch_gate;
mod profiling;
mod readiness;
mod render_entry;
pub(crate) mod scene;
mod scene_submit;
mod shadow_cache;
pub(crate) mod shadows;
mod trace_policy;
mod visibility_control;
pub(crate) mod ui_node_surface;
mod windowing;
mod world_tick;

pub(super) use super::controller::RuntimeRenderController;
pub(super) use frame_submit::{record_draw_list, record_render_phase};
